---
- hosts: server
  remote_user: root
  become: true
  gather_facts: false
  # Ansible requires python2, which is not installed by default on Ubuntu Xenial
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:
    - name: install nodejs
      include_role:
        name: SimpliField.node
    - name: install nginx
      include_role:
        name: nginxinc.nginx-oss
    - name: Creates directory www
      file: path=/var/www/html state=directory
    - name: install bud-e-back 
      git:
        repo: 'https://github.com/insset-bud-e/bud-e-back.git'
        dest: /var/www/html/bud-e-back
      