---
- hosts: server
  remote_user: root
  become: true
  gather_facts: false
  # Ansible requires python2, which is not installed by default on Ubuntu Xenial
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:
    #-----------------------------
    # install pip for docker-py
    #-----------------------------
    - name: check to see if pip is already installed
      command: "pip --version"
      ignore_errors: true
      register: pip_is_installed
      changed_when: false
    - block:
      - name: download get-pip.py
        get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp
      - name: install pip
        command: "python /tmp/get-pip.py"
      - name: delete get-pip.py
        file: state=absent path=/tmp/get-pip.py
      when: pip_is_installed.rc != 0

    #-----------------------------
    # install docker and docker-py
    #-----------------------------
    - name: Install docker with script
      script: scripts/docker-install.sh

    - name: Install docker-py
      shell: "pip install docker-py"

    #-----------------------------
    # install and run container bud-e-front
    #-----------------------------
    - name: remove all container 
      shell: "docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)"

    - name: install bud-e-front 
      git:
        repo: 'https://github.com/insset-bud-e/bud-e-front.git'
        dest: /tmp/bud-e-front
        update: no

    # copy dockerfile in project source 
    - name : copy docker file
      copy:
        src: /home/callot/Projet/ansible/nodejs-ansible/bud-e-front/
        dest: /tmp/bud-e-front/
        directory_mode: yes
            
    - name: build the image bud-e-front
      docker_image: 
        path: "/tmp/bud-e-front" 
        name: "fre3x/bud-e-front" 
        state: build 
        container_limits:
          memswap: 0
    
    - name: run bud-e-front container
      docker:
        name: bud-e-front
        image: fre3x/bud-e-front
        state: started
        log_driver: syslog
        ports: 
        - "8080:8080"
        volumes:
          - /data
        

    
      