galaxy_info:
  author: Sébastien Elet
  description: Nodejs
  company: SimpliField
  license: BSD
  min_ansible_version: 2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - utopic
    - vivid
    - wily
    - xenial
  galaxy_tags:
    - node
    - nodejs
    - javascript
dependencies:
- role: SimpliField.packages
  packages:
  - apt-transport-https
  - python-pycurl
  packages_update_cache: "{{ nodejs_packages_update_cache }}"
