FROM    centos:centos6

# Enable Extra Packages for Enterprise Linux (EPEL) for CentOS
RUN     yum install -y epel-release
# Install Node.js and npm
RUN     yum install -y nodejs npm

# Bundle app source
COPY . /src

# Install app dependencies
COPY package.json /src/package.json
RUN cd /src; npm install --production

EXPOSE  8080
CMD cd /src; npm run build --report
