# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
# 
# Vagrant config 
Vagrant.configure(2) do |config|
  # distro : 
  config.vm.box = "ubuntu/xenial64"
  # configuration virtualbox : 	
  config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
      # Customize the name of VM:
      vb.name = "bud-e-VM"
     end
  # ip configuration : 
  config.vm.network "forwarded_port", guest: 8080, host: 8080,
  auto_correct: true
  config.vm.network "private_network", ip: "192.168.100.1",
  auto_config: false
  # ssh config for generate private key : 
  config.vm.provision "shell" do |s|
    ssh_insecure_key = File.readlines("#{Dir.home}/.vagrant.d/insecure_private_key").first.strip
    s.inline = <<-SHELL
    	echo #{ssh_insecure_key} >> /home/vagrant/.ssh/id_rsa
    	chown vagrant /home/vagrant/.ssh/id_rsa
    	chmod 400 /home/vagrant/.ssh/id_rsa
    SHELL
  end
end
